### ISSUE TITLE
你好, 我配置和你完全一样, 但安装完系统之后重启过wifi就无法打开了

### ISSUE THREAD

**Issue by Liuthx** [DJ-clamp/MSI-B660M-MORTAR-WIFI_Hackintosh_12490F_XFXrx480-8G#1]
安装期间wifi正常, 系统是macos13, 安装完重启之后wifi就无法打开了, 蓝牙正常, 原因可能是什么呀

**Comment by DJ-clamp** [comment]
可能是USB接口的分配问题，删除[UTBMap.kext](https://github.com/DJ-clamp/MSI-B660M-MORTAR-WIFI_Hackintosh_12490F_XFXrx480-8G/tree/main/EFI/OC/Kexts/UTBMap.kext/Contents)测试看看。

**Comment by Liuthx** [comment]
我清了一下nvram就好了...
